<?php get_header(); ?>
<section class="hero small"><div class="pin narrow"><div class="eyebrow">About <?php echo esc_html(get_bloginfo('name') ?: 'NOVA'); ?></div><h1>We've run the front desk, the dispatch board and the month-end close. That's why we automate them carefully.</h1><p class="lede">NOVA was started by <?php echo esc_html(nova_site('founder')); ?> after <?php echo esc_html(nova_site('years')); ?> years working in and around small businesses — the kind where the owner answers the phone, writes the quotes, and does the books on Sunday. We build AI for those businesses the way we'd want it built for our own: inside the tools you have, measured honestly, and never out of your control.</p></div></section>
<section class="psec"><div class="pin"><div class="grid3">
  <div class="card"><h3>What we believe</h3><p>Automation should give people their lunch break back, not their pink slip. Every business we've worked with kept their team; the team stopped drowning.</p></div>
  <div class="card"><h3>What we're not</h3><p>Not an agency selling hours. Not a software vendor selling seats. We're the operators who set it up, measure it, and stay on the hook for the number.</p></div>
  <div class="card"><h3>How we're paid</h3><p>Fixed-scope projects and month-to-month support you can cancel with 30 days' notice. No percentage of your spend, no lock-in, no accounts we own.</p></div>
</div></div></section>
<section class="psec alt"><div class="pin"><div class="eyebrow">What we do</div><h2>Four services, one standard.</h2><?php echo nova_pillar_cards(); ?></div></section>
<section class="psec"><div class="pin narrow"><div class="eyebrow">Experience</div><h2>Where the <?php echo esc_html(nova_site('years')); ?> years went.</h2><?php echo nova_pains(['Operating and advising owner-led businesses in the trades, healthcare and professional services','Implementing and integrating the platforms our clients run on — field service, practice management, CRM, accounting','Building and managing AI voice, messaging and document automation in production, with the compliance work that goes with it','Turning messy processes into SOPs, dashboards and repeatable systems'], true); ?></div></section>
<?php if (get_the_content()) : ?><section class="psec alt"><div class="pin narrow"><?php the_content(); ?></div></section><?php endif; ?>
<?php echo nova_cta_block(); get_footer(); ?>
