<?php get_header(); $d = nova_data(); $ev = $d['EVIDENCE'];
$lens = [['Revenue leaks','Where do customers try to buy and fail?','Phone report, website or store analytics, CRM, booking system','Missed calls, slow lead replies, abandoned carts, no-shows, unfollowed quotes'],['Hours','Where do people copy, chase, or write the same thing repeatedly?','Ask each staff member; the inbox; the task they\'d never do again','Re-keying, document chasing, invoice follow-up, inbox triage, quote writing'],['Cash & margin','Where is money slow, wrong, or unknown?','AR aging, bill volume, job costs, the date the books closed','Late invoices, duplicate payments, unpriced jobs, late close, no dashboard']];
$ex = [['E-commerce and websites',['Most carts abandoned with no recovery sequence; \'where is my order\' answered by hand hours later; product pages with thin copy','Returns handled one email at a time; supplier orders typed in from PDFs','Sales tax across states done by hand; stockouts on the best-selling items'],['Cart-recovery flows, an order-status support agent, catalog copy at scale','Returns automation, order entry from documents','Tax automation, reorder points and stockout warnings'],'baymard'],
  ['Marketing and lead generation',['Ads running, but leads contacted hours later or not at all; past customers never emailed; a handful of reviews next to a competitor\'s hundreds','Every social post written by the owner at night; nobody knows which ads work','Nobody knows which lead source pays'],['Instant lead response with follow-up until a yes or no, reactivation campaigns, a review engine','A content system built from the business\'s own jobs, a Monday marketing summary','Lead-source tracking on one page'],'hbr'],
  ['Operations — agents that do the chasing',['Receivables aging while the office manager avoids the collections call','Hundreds of bills keyed by hand; tax documents chased by phone every spring','Calls missed while the team is with customers; recalls and reminders never sent'],['A collections agent: invoice on job close, polite escalating sequence, disputes to a human','A back-office agent for capture, coding and approvals; document-request sequences','A front-desk agent and a scheduling/recall agent'],'qbLate'],
  ['Professional practices — law, medical, accounting',['After-hours intake to voicemail; consults arriving with no facts','The partner answers the same policy and pricing questions daily; contracts read at midnight','Patient or client balances aged 90+ days'],['An intake agent and pre-visit questionnaires','A private knowledge assistant (on-prem where required), contract review with obligation calendars','A balance follow-up agent'],'cochrane']];
$steps = [['Ten minutes of pre-work','A short form: the systems you use, who does what, the numbers you check and the ones you wish you had. It means the session starts with facts, not guesses.'],['Walk the customer\'s journey','Your team narrates how a customer actually moves through the business — <b>find → contact → book or buy → deliver → bill → collect → return</b> — while we draw it. At each stage: what happens when nobody\'s available, and who\'s waiting?'],['Look through three lenses','Revenue leaks, hours, and cash. You pull each number from a system you already own, on screen, with us. The gaps show up on their own.'],['Score the opportunity cards','Every finding becomes a one-page card. We write the top half — what happens today, what it costs, what \'after\' looks like. You and your team score the bottom half.'],['Prioritize together','Cards go on a grid of impact against ease. The top-right corner is the pilot. Anything that touches customers runs in shadow mode first.'],['The roadmap','A week later: your baseline, the ranked opportunities, a pilot proposal for #1 and what #2 and #3 look like after it works. Presented live, ending with a start date — or an honest \'not yet\'.']]; ?>
<section class="hero small"><div class="pin narrow"><div class="eyebrow">Finding opportunities</div><h1>You know where the time goes. We help you see what it costs — and what to do first.</h1><p class="lede">Our discovery process is done with you and your team, not to you. In one working session you map how a customer moves through your business, pull your own numbers, and score the opportunities yourselves. You walk away with the map and the list whether or not you hire us.</p><div class="pills" style="gap:10px;margin-top:8px"><a class="pbtn big" href="<?php echo esc_url(nova_site('bookingUrl')); ?>"><?php echo nova_cta_text(); ?></a></div></div></section>
<section class="psec"><div class="pin"><div class="eyebrow">The process</div><h2>One form, one session, one scored list.</h2><div class="steps"><?php foreach ($steps as $i => $s) echo '<div class="step"><div class="sn">' . $i . '</div><h3>' . $s[0] . '</h3><p>' . $s[1] . '</p></div>'; ?></div></div></section>
<section class="psec alt"><div class="pin"><div class="eyebrow">Step 2</div><h2>Three lenses, three sources you already have.</h2><div class="tw"><table><thead><tr><th>Lens</th><th>The question</th><th>Where the number lives</th><th>What usually turns up</th></tr></thead><tbody><?php foreach ($lens as $r) echo '<tr><td><b>' . $r[0] . '</b></td><td>' . $r[1] . '</td><td class="small">' . $r[2] . '</td><td class="small">' . $r[3] . '</td></tr>'; ?></tbody></table></div></div></section>
<section class="psec"><div class="pin"><div class="eyebrow">Examples</div><h2>What the session finds, by kind of business.</h2><div class="exgrid"><?php foreach ($ex as $e) { $v = $ev[$e[3]]; echo '<div class="excard"><h3>' . $e[0] . '</h3><div class="exrow"><div><div class="eyebrow">What we usually find</div><ul>'; foreach ($e[1] as $x) echo '<li>' . $x . '</li>'; echo '</ul></div><div><div class="eyebrow">What it becomes</div><ul>'; foreach ($e[2] as $x) echo '<li>' . $x . '</li>'; echo '</ul></div></div><div class="exev"><b>' . $v['stat'] . '</b> ' . $v['text'] . ' <a class="evsrc" href="' . esc_url($v['url']) . '" target="_blank" rel="noopener">' . $v['src'] . ' ↗</a></div></div>'; } ?></div></div></section>
<section class="psec alt"><div class="pin narrow"><div class="eyebrow">Step 3</div><h2>The opportunity card your team scores.</h2><div class="sample"><span class="eyebrow">Sample card</span><pre>OPPORTUNITY: After-hours calls go to voicemail
Today:   calls missed each month (from your phone report) × your booking rate × your average job
After:   a front-desk agent answers, books into your system, transfers emergencies
Service: Agent Hiring       Effort: about 3 weeks       Risk: low — shadow mode first
────────────────────────────────────────────────────────────
Your team scores (1–5):   Pain ___   Value ___   Ease ___   We'd actually use it ___
Owner of this problem: ____________     Pilot metric: missed-call rate</pre></div><p class="small muted" style="margin-top:10px">The scoring matters more than it looks. When the office manager gives 'invoice chasing' a five on pain and a five on 'we'd use it', adoption is already half done.</p></div></section>
<section class="psec"><div class="pin narrow"><div class="eyebrow">What you keep</div><h2>Even if you never hire us.</h2><?php echo nova_pains(['The journey map of your own business, drawn with your team','Your numbers in one place — probably for the first time','A scored list of where the money and hours are going','A clear first step, and an honest opinion on whether it\'s worth taking'], true); ?></div></section>
<?php echo nova_evidence_block(['mckGenAI','mckEmail','qbLate','chamber'], 'What the research says about where the opportunities are.'); echo nova_cta_block(); get_footer(); ?>
